### ISSUE TITLE
Troubleshooting help

### ISSUE THREAD

**Issue by georginaalbadri** [BernsteinLab/Calculate_Myeloid_cNMF_Usage#1] opened 2024-01-12 13:21 UTC
Hello, I have a h5ad matrix processed using scanpy, but I am getting an error 'Warning: Error in py_call_impl: OSError: Could not find/load shared object file' when using the shiny app locally. On the website, it is also not working and disconnects me without any error warning. I am able to run the Demo data with no issue.

My adata.var has the following columns: 
highly_variable | means | dispersions | dispersions_norm | mean | std
And the rows are, as far as I know, the standard gene symbols. 

The adata.obs has headings including cell type, sample, condition etc. The rows are the cell identifiers with naming system e.g. 'Sequence1-A01-B01_C1-1'. 

The data adata.X is of shape (569, 3000) i.e. 569 cells, 3000 genes. 

Please let me know if you can see something here that is not compatible and may lead to the error. Thanks in advance.

**Comment by chadielfarran** [comment] 2024-01-16 18:16
Hi Georgina,

Are the 3000 genes included in the matrix just the variable genes? Are there genes shared between the 3000 genes in your matrix and the genes in the Gene Spectra file? 

If not, can you try loading the h5ad matrix with a complete and normalized gene list?

**Comment by chadielfarran** [comment] 2024-01-23 17:46
I have modified the code for the tool.  After obtaining a complete normalized matrix (with all genes), please try re-running the tool locally. I will fix the online version soon as well. Thank you for reporting.

**Comment by chadielfarran** [comment] 2024-02-20 16:55
I am closing this session as the local and online tools have been modified, and we believe the issue is fixed. Feel free to reopen if the issue is still occurring in your system.

**Closed as completed by chadielfarran** 2024-02-20 16:55 UTC
Labels: bug
